import type {Metadata} from "next";
import {Bricolage_Grotesque, Onest} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {Button} from "@/components/ui/button";
import {
    NavigationMenu, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, navigationMenuTriggerStyle,
} from "@/components/ui/navigation-menu";
import * as React from "react";
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarGroup,
    SidebarGroupContent,
    SidebarHeader,
    SidebarInset,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
    SidebarProvider,
} from "@/components/ui/sidebar";
import {Item, ItemHeader, ItemMedia} from "@/components/ui/item";
import {CustomSidebarTrigger} from "@/components/sidebar-trigger";
import {Avatar, AvatarFallback, AvatarImage} from "@/components/ui/avatar";
import {ThemeProvider} from "next-themes";


const onest = Onest({
    variable: "--font-onest", subsets: ["latin"],
});

const bricolage_g = Bricolage_Grotesque({
    variable: "--font-bricolage-grotesque", subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<html lang="it" suppressHydrationWarning>
    <body className={`${bricolage_g.className} antialiased`}>
    <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem
        disableTransitionOnChange
    >

        <SidebarProvider>
            <SidebarInset>
                <div className="sticky top-0 backdrop-filter backdrop-blur-sm border-b z-[500]">
                    <div className="container mx-auto px-4">
                        <div className="flex justify-between items-center h-16">
                            <div className="flex-2 flex justify-start">
                                <Item>
                                    <ItemHeader>
                                        <ItemMedia>
                                            <div className="*:data-[slot=avatar]:ring-background flex -space-x-2 ">

                                                <Avatar>
                                                    <AvatarImage
                                                        src="loghi/logo_olimpia.jpg"
                                                        alt="OLIMPIA MILANO"
                                                    />
                                                    <AvatarFallback>OM</AvatarFallback>
                                                </Avatar>
                                                <Avatar>
                                                    <AvatarImage
                                                        src="loghi/logo_bottoni.png"
                                                        alt="LSS P. BOTTONI"
                                                    />
                                                    <AvatarFallback>LB</AvatarFallback>
                                                </Avatar>
                                            </div>
                                        </ItemMedia>
                                        <Link href="/">
                                            <code
                                                className={`${bricolage_g.className} font-black`}
                                            >
                                                OLIMPIA.BOTTONI
                                            </code>
                                        </Link>
                                    </ItemHeader>
                                </Item>
                            </div>

                            <div className="flex-none hidden md:block">
                                <NavigationMenu>
                                    <NavigationMenuList>
                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <Link href="/">Home</Link>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>

                                        <NavigationMenuItem>
                                            <NavigationMenuLink
                                                asChild
                                                className={navigationMenuTriggerStyle()}
                                            >
                                                <Link href="/organigramma">Team</Link>
                                            </NavigationMenuLink>
                                        </NavigationMenuItem>


                                    </NavigationMenuList>
                                </NavigationMenu>
                            </div>
                            <div className="md:flex-2 flex-1 flex justify-end items-center">

                                <Button
                                    asChild
                                    variant="default"
                                    className="hidden md:inline-flex"
                                >
                                    <Link href="https://tickets.olimpiamilano.com/">
                                        ACQUISTA ORA!
                                    </Link>
                                </Button>
                                <CustomSidebarTrigger/>
                            </div>
                        </div>
                    </div>
                </div>
                {children}
                <footer className="bg-background border-t py-8 mt-16">
                    <div className="container mx-auto px-4 text-center text-sm text-muted-foreground">

                        <p className="mt-2">
                            Built with ❤️ by{" "}
                            <Link
                                href="https://riccardo.is-a.dev"
                                className="hover:underline"
                            >
                                Riccardo Debellini
                            </Link>
                        </p>
                        <p>
                            &copy; {new Date().getFullYear()} Riccardo Debellini. All
                            rights reserved.
                        </p>
                    </div>
                </footer>
                <Sidebar side="right" className="md:hidden">
                    <SidebarHeader>
                        <SidebarMenu>
                            <SidebarMenuItem>
                                <Item>
                                    <ItemHeader>
                                        <ItemMedia>
                                            <div className="*:data-[slot=avatar]:ring-background flex -space-x-2 ">

                                                <Avatar>
                                                    <AvatarImage
                                                        src="loghi/logo_olimpia.jpg"
                                                        alt="OLIMPIA MILANO"
                                                    />
                                                    <AvatarFallback>OM</AvatarFallback>
                                                </Avatar>
                                                <Avatar>
                                                    <AvatarImage
                                                        src="loghi/logo_bottoni.png"
                                                        alt="LSS P. BOTTONI"
                                                    />
                                                    <AvatarFallback>LB</AvatarFallback>
                                                </Avatar>
                                            </div>
                                        </ItemMedia>
                                        <Link href="/">
                                            <code
                                                className={`${bricolage_g.className} font-black`}
                                            >
                                                OLIMPIA.BOTTONI
                                            </code>
                                        </Link>
                                    </ItemHeader>
                                </Item>
                            </SidebarMenuItem>
                        </SidebarMenu>
                    </SidebarHeader>

                    <SidebarContent>
                        <SidebarGroup>
                            <SidebarGroupContent>
                                <SidebarMenu>
                                    <SidebarMenuItem>
                                        <SidebarMenuButton asChild>
                                            <Link href="/" className="font-medium">
                                                Home
                                            </Link>
                                        </SidebarMenuButton>
                                    </SidebarMenuItem>
                                    <SidebarMenuItem>
                                        <SidebarMenuButton asChild>
                                            <Link href="/organigramma" className="font-medium">
                                                Team
                                            </Link>
                                        </SidebarMenuButton>
                                    </SidebarMenuItem>

                                </SidebarMenu>
                            </SidebarGroupContent>
                        </SidebarGroup>
                    </SidebarContent>
                    <SidebarFooter>

                        <Button size="lg" variant='default' className='w-full' asChild>
                            <Link href="https://tickets.olimpiamilano.com/">
                                ACQUISTA ORA!
                            </Link>
                        </Button>

                    </SidebarFooter>
                </Sidebar>
            </SidebarInset>
        </SidebarProvider>
    </ThemeProvider>
    </body>
    </html>);
}
